- name: Fedora | Install kubernetes master
  package:
    name: kubernetes-master
    state: latest
    enablerepo: "updates-testing"
  notify:
    - restart daemons

- name: Fedora | Install kubernetes node
  package:
    name: kubernetes-node
    state: latest
    enablerepo: "updates-testing"
  notify:
    - restart daemons
  when: networking == 'opencontrail'
