- name: Generic | Install kubernetes master
  pacakge:
    name: kubernetes-master
    state: latest
  notify:
    - restart daemons
- name: Generic | Install kubernetes node
  package:
    name: kubernetes-node
    state: latest
  notify:
    - restart daemons
  when: networking == 'opencontrail'
